/* Generated by re2c 3.0 */
#line 1 "lexer/mgmt_protocol.re"
#include "../include/mgmt_protocol.re.h"
#include <stdbool.h>
#include <string.h>
#line 18 "lexer/mgmt_protocol.re"


#line 23 "lexer/mgmt_protocol.re"


MgmtCommand parseMgmtRequest(Input *in, char **arg, size_t *argLen, size_t *len)
{
	char yych;
	char *args = NULL, *arge = NULL, *end;
	MgmtCommand result;
	
#line 19 "./src/mgmt_protocol.re.c"
#define yyt1 in->yyt1
#define yyt2 in->yyt2
#line 30 "lexer/mgmt_protocol.re"


#define YYGETSTATE in->state
#line 26 "./src/mgmt_protocol.re.c"
switch (YYGETSTATE) {
	default: goto yy0;
	case 0:
		if (in->lim <= in->cur) goto yy75;
		goto yyFillLabel0;
	case 1:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel1;
	case 2:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel2;
	case 3:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel3;
	case 4:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel4;
	case 5:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel5;
	case 6:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel6;
	case 7:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel7;
	case 8:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel8;
	case 9:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel9;
	case 10:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel10;
	case 11:
		if (in->lim <= in->cur) goto yy3;
		goto yyFillLabel11;
	case 12:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel12;
	case 13:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel13;
	case 14:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel14;
	case 15:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel15;
	case 16:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel16;
	case 17:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel17;
	case 18:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel18;
	case 19:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel19;
	case 20:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel20;
	case 21:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel21;
	case 22:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel22;
	case 23:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel23;
	case 24:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel24;
	case 25:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel25;
	case 26:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel26;
	case 27:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel27;
	case 28:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel28;
	case 29:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel29;
	case 30:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel30;
	case 31:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel31;
	case 32:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel32;
	case 33:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel33;
	case 34:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel34;
	case 35:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel35;
	case 36:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel36;
	case 37:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel37;
	case 38:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel38;
	case 39:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel39;
	case 40:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel40;
	case 41:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel41;
	case 42:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel42;
	case 43:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel43;
	case 44:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel44;
	case 45:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel45;
	case 46:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel46;
	case 47:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel47;
	case 48:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel48;
	case 49:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel49;
	case 50:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel50;
	case 51:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel51;
	case 52:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel52;
	case 53:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel53;
	case 54:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel54;
	case 55:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel55;
	case 56:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel56;
	case 57:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel57;
	case 58:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel58;
	case 59:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel59;
	case 60:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel60;
	case 61:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel61;
	case 62:
		if (in->lim <= in->cur) goto yy17;
		goto yyFillLabel62;
	case 63:
		if (in->lim <= in->cur) goto yy196;
		goto yyFillLabel63;
	case 64:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel64;
	case 65:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel65;
	case 66:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel66;
	case 67:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel67;
	case 68:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel68;
	case 69:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel69;
	case 70:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel70;
	case 71:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel71;
	case 72:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel72;
	case 73:
		if (in->lim <= in->cur) goto yy78;
		goto yyFillLabel73;
	case 74:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel74;
	case 75:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel75;
	case 76:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel76;
	case 77:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel77;
	case 78:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel78;
	case 79:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel79;
	case 80:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel80;
	case 81:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel81;
	case 82:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel82;
	case 83:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel83;
	case 84:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel84;
	case 85:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel85;
	case 86:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel86;
	case 87:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel87;
	case 88:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel88;
	case 89:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel89;
	case 90:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel90;
	case 91:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel91;
	case 92:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel92;
	case 93:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel93;
	case 94:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel94;
	case 95:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel95;
	case 96:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel96;
	case 97:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel97;
	case 98:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel98;
	case 99:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel99;
	case 100:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel100;
	case 101:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel101;
	case 102:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel102;
	case 103:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel103;
	case 104:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel104;
	case 105:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel105;
	case 106:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel106;
	case 107:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel107;
	case 108:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel108;
	case 109:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel109;
	case 110:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel110;
	case 111:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel111;
	case 112:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel112;
	case 113:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel113;
	case 114:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel114;
	case 115:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel115;
	case 116:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel116;
	case 117:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel117;
	case 118:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel118;
	case 119:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel119;
	case 120:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel120;
	case 121:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel121;
	case 122:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel122;
	case 123:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel123;
	case 124:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel124;
	case 125:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel125;
	case 126:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel126;
	case 127:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel127;
	case 128:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel128;
	case 129:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel129;
	case 130:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel130;
	case 131:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel131;
	case 132:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel132;
	case 133:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel133;
	case 134:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel134;
	case 135:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel135;
	case 136:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel136;
	case 137:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel137;
	case 138:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel138;
	case 139:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel139;
	case 140:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel140;
	case 141:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel141;
	case 142:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel142;
	case 143:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel143;
	case 144:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel144;
	case 145:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel145;
	case 146:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel146;
	case 147:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel147;
	case 148:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel148;
	case 149:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel149;
	case 150:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel150;
	case 151:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel151;
	case 152:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel152;
	case 153:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel153;
	case 154:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel154;
	case 155:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel155;
	case 156:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel156;
	case 157:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel157;
	case 158:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel158;
	case 159:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel159;
	case 160:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel160;
	case 161:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel161;
	case 162:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel162;
	case 163:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel163;
	case 164:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel164;
	case 165:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel165;
	case 166:
		if (in->lim <= in->cur) goto yy91;
		goto yyFillLabel166;
}
#line 33 "lexer/mgmt_protocol.re"

#undef YYGETSTATE

	for (;;)
	{
		
#line 538 "./src/mgmt_protocol.re.c"

yy0:
	switch (in->cond) {
		case yycpass: goto yyc_pass;
		case yyctrns: goto yyc_trns;
	}
/* *********************************** */
yyc_pass:
yyFillLabel0:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy4;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'M':
		case 'N':
		case 'O':
		case 'R':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'r':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy5;
		case 'B':
		case 'b': goto yy6;
		case 'C':
		case 'c': goto yy7;
		case 'D':
		case 'd': goto yy8;
		case 'L':
		case 'l': goto yy9;
		case 'P':
		case 'p': goto yy10;
		case 'Q':
		case 'q': goto yy11;
		case 'S':
		case 's': goto yy12;
		case 'T':
		case 't': goto yy13;
		case 'U':
		case 'u': goto yy14;
		default:
			if (in->lim <= in->cur) {
				in->state = 0;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy2;
	}
yy2:
	++in->cur;
yy3:
	in->state = -1;
#line 69 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 660 "./src/mgmt_protocol.re.c"
yy4:
	++in->cur;
yyFillLabel1:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy15;
		default:
			if (in->lim <= in->cur) {
				in->state = 1;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy5:
	in->mar = ++in->cur;
yyFillLabel2:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default:
			if (in->lim <= in->cur) {
				in->state = 2;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy6:
	in->mar = ++in->cur;
yyFillLabel3:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'U':
		case 'u': goto yy20;
		default:
			if (in->lim <= in->cur) {
				in->state = 3;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy7:
	in->mar = ++in->cur;
yyFillLabel4:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'A':
		case 'a': goto yy21;
		default:
			if (in->lim <= in->cur) {
				in->state = 4;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy8:
	in->mar = ++in->cur;
yyFillLabel5:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'I':
		case 'i': goto yy22;
		default:
			if (in->lim <= in->cur) {
				in->state = 5;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy9:
	in->mar = ++in->cur;
yyFillLabel6:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'I':
		case 'i': goto yy23;
		default:
			if (in->lim <= in->cur) {
				in->state = 6;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy10:
	in->mar = ++in->cur;
yyFillLabel7:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'A':
		case 'a': goto yy24;
		default:
			if (in->lim <= in->cur) {
				in->state = 7;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy11:
	in->mar = ++in->cur;
yyFillLabel8:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'U':
		case 'u': goto yy25;
		default:
			if (in->lim <= in->cur) {
				in->state = 8;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy12:
	in->mar = ++in->cur;
yyFillLabel9:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'E':
		case 'e': goto yy26;
		default:
			if (in->lim <= in->cur) {
				in->state = 9;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy13:
	in->mar = ++in->cur;
yyFillLabel10:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'O':
		case 'o': goto yy27;
		default:
			if (in->lim <= in->cur) {
				in->state = 10;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy14:
	in->mar = ++in->cur;
yyFillLabel11:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		case 'S':
		case 's': goto yy28;
		default:
			if (in->lim <= in->cur) {
				in->state = 11;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy3;
	}
yy15:
	++in->cur;
	in->state = -1;
#line 68 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 1769 "./src/mgmt_protocol.re.c"
yy16:
	++in->cur;
yyFillLabel12:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy29;
		default:
			if (in->lim <= in->cur) {
				in->state = 12;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy17:
	in->cur = in->mar;
	goto yy3;
yy18:
	++in->cur;
yyFillLabel13:
	yych = *in->cur;
yy19:
	switch (yych) {
		case '\r': goto yy16;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default:
			if (in->lim <= in->cur) {
				in->state = 13;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy20:
	++in->cur;
yyFillLabel14:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 14;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'F':
		case 'f': goto yy30;
		default: goto yy19;
	}
yy21:
	++in->cur;
yyFillLabel15:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 15;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'P':
		case 'p': goto yy31;
		default: goto yy19;
	}
yy22:
	++in->cur;
yyFillLabel16:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 16;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy32;
		default: goto yy19;
	}
yy23:
	++in->cur;
yyFillLabel17:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 17;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy33;
		default: goto yy19;
	}
yy24:
	++in->cur;
yyFillLabel18:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 18;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy34;
		default: goto yy19;
	}
yy25:
	++in->cur;
yyFillLabel19:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 19;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'I':
		case 'i': goto yy35;
		default: goto yy19;
	}
yy26:
	++in->cur;
yyFillLabel20:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 20;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy36;
		default: goto yy19;
	}
yy27:
	++in->cur;
yyFillLabel21:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 21;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'K':
		case 'k': goto yy37;
		default: goto yy19;
	}
yy28:
	++in->cur;
yyFillLabel22:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 22;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'E':
		case 'e': goto yy38;
		default: goto yy19;
	}
yy29:
	++in->cur;
	in->state = -1;
#line 67 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 2036 "./src/mgmt_protocol.re.c"
yy30:
	++in->cur;
yyFillLabel23:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 23;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'F':
		case 'f': goto yy39;
		default: goto yy19;
	}
yy31:
	++in->cur;
yyFillLabel24:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 24;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'A':
		case 'a': goto yy40;
		default: goto yy19;
	}
yy32:
	++in->cur;
yyFillLabel25:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 25;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy41;
		default: goto yy19;
	}
yy33:
	++in->cur;
yyFillLabel26:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 26;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy42;
		default: goto yy19;
	}
yy34:
	++in->cur;
yyFillLabel27:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 27;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy42;
		default: goto yy19;
	}
yy35:
	++in->cur;
yyFillLabel28:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 28;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy43;
		default: goto yy19;
	}
yy36:
	++in->cur;
yyFillLabel29:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 29;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case '-': goto yy44;
		default: goto yy19;
	}
yy37:
	++in->cur;
yyFillLabel30:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 30;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'E':
		case 'e': goto yy45;
		default: goto yy19;
	}
yy38:
	++in->cur;
yyFillLabel31:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 31;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'R':
		case 'r': goto yy34;
		default: goto yy19;
	}
yy39:
	++in->cur;
yyFillLabel32:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 32;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy46;
		default: goto yy19;
	}
yy40:
	++in->cur;
yyFillLabel33:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy47;
		case ' ': goto yy40;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default:
			if (in->lim <= in->cur) {
				in->state = 33;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy41:
	++in->cur;
yyFillLabel34:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 34;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'E':
		case 'e': goto yy48;
		default: goto yy19;
	}
yy42:
	++in->cur;
yyFillLabel35:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 35;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case ' ': goto yy49;
		default: goto yy19;
	}
yy43:
	++in->cur;
yyFillLabel36:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy50;
		case ' ': goto yy43;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default:
			if (in->lim <= in->cur) {
				in->state = 36;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy44:
	++in->cur;
yyFillLabel37:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 37;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'B':
		case 'b': goto yy51;
		case 'D':
		case 'd': goto yy52;
		default: goto yy19;
	}
yy45:
	++in->cur;
yyFillLabel38:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 38;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'N':
		case 'n': goto yy53;
		default: goto yy19;
	}
yy46:
	++in->cur;
yyFillLabel39:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 39;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'I':
		case 'i': goto yy54;
		default: goto yy19;
	}
yy47:
	++in->cur;
yyFillLabel40:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy55;
		default:
			if (in->lim <= in->cur) {
				in->state = 40;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy48:
	++in->cur;
yyFillLabel41:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 41;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'C':
		case 'c': goto yy56;
		default: goto yy19;
	}
yy49:
	++in->cur;
yyFillLabel42:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy57;
		default:
			if (in->lim <= in->cur) {
				in->state = 42;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy49;
	}
yy50:
	++in->cur;
yyFillLabel43:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy58;
		default:
			if (in->lim <= in->cur) {
				in->state = 43;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy51:
	++in->cur;
yyFillLabel44:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 44;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'U':
		case 'u': goto yy20;
		default: goto yy19;
	}
yy52:
	++in->cur;
yyFillLabel45:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 45;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'I':
		case 'i': goto yy22;
		default: goto yy19;
	}
yy53:
	++in->cur;
yyFillLabel46:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 46;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default: goto yy60;
	}
yy54:
	++in->cur;
yyFillLabel47:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 47;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'Z':
		case 'z': goto yy61;
		default: goto yy19;
	}
yy55:
	++in->cur;
	in->state = -1;
#line 64 "lexer/mgmt_protocol.re"
	{ result = MGMT_CAPA; break; }
#line 2692 "./src/mgmt_protocol.re.c"
yy56:
	++in->cur;
yyFillLabel48:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 48;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy62;
		default: goto yy19;
	}
yy57:
	++in->cur;
yyFillLabel49:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy63;
		default:
			if (in->lim <= in->cur) {
				in->state = 49;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy58:
	++in->cur;
	in->state = -1;
#line 63 "lexer/mgmt_protocol.re"
	{ result = MGMT_QUIT; break; }
#line 2726 "./src/mgmt_protocol.re.c"
yy59:
	++in->cur;
yyFillLabel50:
	yych = *in->cur;
yy60:
	switch (yych) {
		case '\r': goto yy16;
		case ' ': goto yy59;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:
			yyt1 = in->cur;
			goto yy64;
		default:
			if (in->lim <= in->cur) {
				in->state = 50;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy61:
	++in->cur;
yyFillLabel51:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 51;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'E':
		case 'e': goto yy42;
		default: goto yy19;
	}
yy62:
	++in->cur;
yyFillLabel52:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 52;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'O':
		case 'o': goto yy65;
		default: goto yy19;
	}
yy63:
	++in->cur;
	in->state = -1;
#line 66 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_ARGS; break; }
#line 2874 "./src/mgmt_protocol.re.c"
yy64:
	++in->cur;
yyFillLabel53:
	yych = *in->cur;
	switch (yych) {
		case '\r':
			yyt2 = in->cur;
			goto yy66;
		case ' ':
			yyt2 = in->cur;
			goto yy67;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy64;
		default:
			if (in->lim <= in->cur) {
				in->state = 53;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy65:
	++in->cur;
yyFillLabel54:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 54;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'R':
		case 'r': goto yy68;
		default: goto yy19;
	}
yy66:
	++in->cur;
yyFillLabel55:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy69;
		default:
			if (in->lim <= in->cur) {
				in->state = 55;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy67:
	++in->cur;
yyFillLabel56:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy66;
		case ' ': goto yy67;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy18;
		default:
			if (in->lim <= in->cur) {
				in->state = 56;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
	}
yy68:
	++in->cur;
yyFillLabel57:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 57;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case '-': goto yy70;
		default: goto yy19;
	}
yy69:
	++in->cur;
	args = yyt1;
	arge = yyt2;
	in->state = -1;
#line 54 "lexer/mgmt_protocol.re"
	{ result = MGMT_TOKEN; break; }
#line 3146 "./src/mgmt_protocol.re.c"
yy70:
	++in->cur;
yyFillLabel58:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 58;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'S':
		case 's': goto yy71;
		default: goto yy19;
	}
yy71:
	++in->cur;
yyFillLabel59:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 59;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy72;
		default: goto yy19;
	}
yy72:
	++in->cur;
yyFillLabel60:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 60;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'A':
		case 'a': goto yy73;
		default: goto yy19;
	}
yy73:
	++in->cur;
yyFillLabel61:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 61;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'T':
		case 't': goto yy74;
		default: goto yy19;
	}
yy74:
	++in->cur;
yyFillLabel62:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 62;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy17;
		case 'U':
		case 'u': goto yy34;
		default: goto yy19;
	}
yy75:
	in->state = -1;
#line 70 "lexer/mgmt_protocol.re"
	{ result = MGMT_INCOMPLETE; break; }
#line 3226 "./src/mgmt_protocol.re.c"
/* *********************************** */
yyc_trns:
yyFillLabel63:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy79;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'M':
		case 'N':
		case 'O':
		case 'R':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'r':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy80;
		case 'B':
		case 'b': goto yy81;
		case 'C':
		case 'c': goto yy82;
		case 'D':
		case 'd': goto yy83;
		case 'L':
		case 'l': goto yy84;
		case 'P':
		case 'p': goto yy85;
		case 'Q':
		case 'q': goto yy86;
		case 'S':
		case 's': goto yy87;
		case 'U':
		case 'u': goto yy88;
		default:
			if (in->lim <= in->cur) {
				in->state = 63;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy77;
	}
yy77:
	++in->cur;
yy78:
	in->state = -1;
#line 69 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 3342 "./src/mgmt_protocol.re.c"
yy79:
	++in->cur;
yyFillLabel64:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy89;
		default:
			if (in->lim <= in->cur) {
				in->state = 64;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy80:
	in->mar = ++in->cur;
yyFillLabel65:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		default:
			if (in->lim <= in->cur) {
				in->state = 65;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy81:
	in->mar = ++in->cur;
yyFillLabel66:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'U':
		case 'u': goto yy94;
		default:
			if (in->lim <= in->cur) {
				in->state = 66;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy82:
	in->mar = ++in->cur;
yyFillLabel67:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'A':
		case 'a': goto yy95;
		default:
			if (in->lim <= in->cur) {
				in->state = 67;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy83:
	in->mar = ++in->cur;
yyFillLabel68:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'I':
		case 'i': goto yy96;
		default:
			if (in->lim <= in->cur) {
				in->state = 68;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy84:
	in->mar = ++in->cur;
yyFillLabel69:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'I':
		case 'i': goto yy97;
		default:
			if (in->lim <= in->cur) {
				in->state = 69;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy85:
	in->mar = ++in->cur;
yyFillLabel70:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'A':
		case 'a': goto yy98;
		default:
			if (in->lim <= in->cur) {
				in->state = 70;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy86:
	in->mar = ++in->cur;
yyFillLabel71:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'U':
		case 'u': goto yy99;
		default:
			if (in->lim <= in->cur) {
				in->state = 71;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy87:
	in->mar = ++in->cur;
yyFillLabel72:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'E':
		case 'e': goto yy100;
		case 'T':
		case 't': goto yy101;
		default:
			if (in->lim <= in->cur) {
				in->state = 72;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy88:
	in->mar = ++in->cur;
yyFillLabel73:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		case 'S':
		case 's': goto yy102;
		default:
			if (in->lim <= in->cur) {
				in->state = 73;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy78;
	}
yy89:
	++in->cur;
	in->state = -1;
#line 68 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 4342 "./src/mgmt_protocol.re.c"
yy90:
	++in->cur;
yyFillLabel74:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy103;
		default:
			if (in->lim <= in->cur) {
				in->state = 74;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy91:
	in->cur = in->mar;
	goto yy78;
yy92:
	++in->cur;
yyFillLabel75:
	yych = *in->cur;
yy93:
	switch (yych) {
		case '\r': goto yy90;
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		default:
			if (in->lim <= in->cur) {
				in->state = 75;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy94:
	++in->cur;
yyFillLabel76:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 76;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'F':
		case 'f': goto yy104;
		default: goto yy93;
	}
yy95:
	++in->cur;
yyFillLabel77:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 77;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'P':
		case 'p': goto yy105;
		default: goto yy93;
	}
yy96:
	++in->cur;
yyFillLabel78:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 78;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy106;
		default: goto yy93;
	}
yy97:
	++in->cur;
yyFillLabel79:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 79;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy107;
		default: goto yy93;
	}
yy98:
	++in->cur;
yyFillLabel80:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 80;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy108;
		default: goto yy93;
	}
yy99:
	++in->cur;
yyFillLabel81:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 81;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'I':
		case 'i': goto yy109;
		default: goto yy93;
	}
yy100:
	++in->cur;
yyFillLabel82:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 82;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy110;
		default: goto yy93;
	}
yy101:
	++in->cur;
yyFillLabel83:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 83;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'A':
		case 'a': goto yy111;
		default: goto yy93;
	}
yy102:
	++in->cur;
yyFillLabel84:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 84;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'E':
		case 'e': goto yy112;
		default: goto yy93;
	}
yy103:
	++in->cur;
	in->state = -1;
#line 67 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_CMD; break; }
#line 4609 "./src/mgmt_protocol.re.c"
yy104:
	++in->cur;
yyFillLabel85:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 85;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'F':
		case 'f': goto yy113;
		default: goto yy93;
	}
yy105:
	++in->cur;
yyFillLabel86:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 86;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'A':
		case 'a': goto yy114;
		default: goto yy93;
	}
yy106:
	++in->cur;
yyFillLabel87:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 87;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy115;
		default: goto yy93;
	}
yy107:
	++in->cur;
yyFillLabel88:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 88;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy116;
		default: goto yy93;
	}
yy108:
	++in->cur;
yyFillLabel89:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 89;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy116;
		default: goto yy93;
	}
yy109:
	++in->cur;
yyFillLabel90:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 90;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy117;
		default: goto yy93;
	}
yy110:
	++in->cur;
yyFillLabel91:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 91;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '-': goto yy118;
		default: goto yy93;
	}
yy111:
	++in->cur;
yyFillLabel92:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 92;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy119;
		default: goto yy93;
	}
yy112:
	++in->cur;
yyFillLabel93:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 93;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'R':
		case 'r': goto yy120;
		default: goto yy93;
	}
yy113:
	++in->cur;
yyFillLabel94:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 94;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy121;
		default: goto yy93;
	}
yy114:
	++in->cur;
yyFillLabel95:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy122;
		case ' ': goto yy114;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		default:
			if (in->lim <= in->cur) {
				in->state = 95;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy115:
	++in->cur;
yyFillLabel96:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 96;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'E':
		case 'e': goto yy123;
		default: goto yy93;
	}
yy116:
	++in->cur;
yyFillLabel97:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 97;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case ' ': goto yy124;
		default: goto yy93;
	}
yy117:
	++in->cur;
yyFillLabel98:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy126;
		case ' ': goto yy117;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		default:
			if (in->lim <= in->cur) {
				in->state = 98;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy118:
	++in->cur;
yyFillLabel99:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 99;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'B':
		case 'b': goto yy127;
		case 'D':
		case 'd': goto yy128;
		default: goto yy93;
	}
yy119:
	++in->cur;
yyFillLabel100:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 100;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy129;
		default: goto yy93;
	}
yy120:
	++in->cur;
yyFillLabel101:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 101;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy130;
		default: goto yy93;
	}
yy121:
	++in->cur;
yyFillLabel102:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 102;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'I':
		case 'i': goto yy131;
		default: goto yy93;
	}
yy122:
	++in->cur;
yyFillLabel103:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy132;
		default:
			if (in->lim <= in->cur) {
				in->state = 103;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy123:
	++in->cur;
yyFillLabel104:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 104;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'C':
		case 'c': goto yy133;
		default: goto yy93;
	}
yy124:
	++in->cur;
yyFillLabel105:
	yych = *in->cur;
yy125:
	switch (yych) {
		case '\r': goto yy134;
		default:
			if (in->lim <= in->cur) {
				in->state = 105;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy126:
	++in->cur;
yyFillLabel106:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy135;
		default:
			if (in->lim <= in->cur) {
				in->state = 106;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy127:
	++in->cur;
yyFillLabel107:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 107;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'U':
		case 'u': goto yy136;
		default: goto yy93;
	}
yy128:
	++in->cur;
yyFillLabel108:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 108;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'I':
		case 'i': goto yy137;
		default: goto yy93;
	}
yy129:
	++in->cur;
yyFillLabel109:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy138;
		case ' ': goto yy129;
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy92;
		default:
			if (in->lim <= in->cur) {
				in->state = 109;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy130:
	++in->cur;
yyFillLabel110:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 110;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '\r': goto yy139;
		case ' ': goto yy140;
		default: goto yy93;
	}
yy131:
	++in->cur;
yyFillLabel111:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 111;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'Z':
		case 'z': goto yy141;
		default: goto yy93;
	}
yy132:
	++in->cur;
	in->state = -1;
#line 64 "lexer/mgmt_protocol.re"
	{ result = MGMT_CAPA; break; }
#line 5297 "./src/mgmt_protocol.re.c"
yy133:
	++in->cur;
yyFillLabel112:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 112;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy142;
		default: goto yy93;
	}
yy134:
	++in->cur;
yyFillLabel113:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy143;
		default:
			if (in->lim <= in->cur) {
				in->state = 113;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy135:
	++in->cur;
	in->state = -1;
#line 63 "lexer/mgmt_protocol.re"
	{ result = MGMT_QUIT; break; }
#line 5331 "./src/mgmt_protocol.re.c"
yy136:
	++in->cur;
yyFillLabel114:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 114;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'F':
		case 'f': goto yy144;
		default: goto yy93;
	}
yy137:
	++in->cur;
yyFillLabel115:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 115;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy145;
		default: goto yy93;
	}
yy138:
	++in->cur;
yyFillLabel116:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy146;
		default:
			if (in->lim <= in->cur) {
				in->state = 116;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy139:
	++in->cur;
yyFillLabel117:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy147;
		default:
			if (in->lim <= in->cur) {
				in->state = 117;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy140:
	++in->cur;
yyFillLabel118:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy139;
		case ' ': goto yy140;
		default:
			if (in->lim <= in->cur) {
				in->state = 118;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy141:
	++in->cur;
yyFillLabel119:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 119;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'E':
		case 'e': goto yy148;
		default: goto yy93;
	}
yy142:
	++in->cur;
yyFillLabel120:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 120;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'O':
		case 'o': goto yy149;
		default: goto yy93;
	}
yy143:
	++in->cur;
	in->state = -1;
#line 66 "lexer/mgmt_protocol.re"
	{ result = MGMT_INVALID_ARGS; break; }
#line 5437 "./src/mgmt_protocol.re.c"
yy144:
	++in->cur;
yyFillLabel121:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 121;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'F':
		case 'f': goto yy150;
		default: goto yy93;
	}
yy145:
	++in->cur;
yyFillLabel122:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 122;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy151;
		default: goto yy93;
	}
yy146:
	++in->cur;
	in->state = -1;
#line 56 "lexer/mgmt_protocol.re"
	{ result = MGMT_STATS; break; }
#line 5473 "./src/mgmt_protocol.re.c"
yy147:
	++in->cur;
	in->state = -1;
#line 57 "lexer/mgmt_protocol.re"
	{ result = MGMT_USERS; break; }
#line 5479 "./src/mgmt_protocol.re.c"
yy148:
	++in->cur;
yyFillLabel123:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 123;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '\r': goto yy152;
		case ' ': goto yy153;
		default: goto yy93;
	}
yy149:
	++in->cur;
yyFillLabel124:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 124;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'R':
		case 'r': goto yy154;
		default: goto yy93;
	}
yy150:
	++in->cur;
yyFillLabel125:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 125;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy155;
		default: goto yy93;
	}
yy151:
	++in->cur;
yyFillLabel126:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 126;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'E':
		case 'e': goto yy156;
		default: goto yy93;
	}
yy152:
	++in->cur;
yyFillLabel127:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy157;
		default:
			if (in->lim <= in->cur) {
				in->state = 127;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy153:
	++in->cur;
yyFillLabel128:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy152;
		case ' ': goto yy153;
		default:
			if (in->lim <= in->cur) {
				in->state = 128;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy154:
	++in->cur;
yyFillLabel129:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 129;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '-': goto yy158;
		default: goto yy93;
	}
yy155:
	++in->cur;
yyFillLabel130:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 130;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'I':
		case 'i': goto yy159;
		default: goto yy93;
	}
yy156:
	++in->cur;
yyFillLabel131:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 131;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'C':
		case 'c': goto yy160;
		default: goto yy93;
	}
yy157:
	++in->cur;
	in->state = -1;
#line 58 "lexer/mgmt_protocol.re"
	{ result = MGMT_GET_BUFFSIZE; break; }
#line 5616 "./src/mgmt_protocol.re.c"
yy158:
	++in->cur;
yyFillLabel132:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 132;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy161;
		default: goto yy93;
	}
yy159:
	++in->cur;
yyFillLabel133:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 133;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'Z':
		case 'z': goto yy162;
		default: goto yy93;
	}
yy160:
	++in->cur;
yyFillLabel134:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 134;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy163;
		default: goto yy93;
	}
yy161:
	++in->cur;
yyFillLabel135:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 135;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy164;
		default: goto yy93;
	}
yy162:
	++in->cur;
yyFillLabel136:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 136;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'E':
		case 'e': goto yy165;
		default: goto yy93;
	}
yy163:
	++in->cur;
yyFillLabel137:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 137;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'O':
		case 'o': goto yy166;
		default: goto yy93;
	}
yy164:
	++in->cur;
yyFillLabel138:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 138;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'A':
		case 'a': goto yy167;
		default: goto yy93;
	}
yy165:
	++in->cur;
yyFillLabel139:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 139;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case ' ': goto yy168;
		default: goto yy93;
	}
yy166:
	++in->cur;
yyFillLabel140:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 140;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'R':
		case 'r': goto yy169;
		default: goto yy93;
	}
yy167:
	++in->cur;
yyFillLabel141:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 141;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy170;
		default: goto yy93;
	}
yy168:
	++in->cur;
yyFillLabel142:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy134;
		case ' ': goto yy168;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			yyt1 = in->cur;
			goto yy171;
		default:
			if (in->lim <= in->cur) {
				in->state = 142;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy169:
	++in->cur;
yyFillLabel143:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 143;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '-': goto yy172;
		default: goto yy93;
	}
yy170:
	++in->cur;
yyFillLabel144:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 144;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'U':
		case 'u': goto yy173;
		default: goto yy93;
	}
yy171:
	++in->cur;
yyFillLabel145:
	yych = *in->cur;
	switch (yych) {
		case '\r':
			yyt2 = in->cur;
			goto yy174;
		case ' ':
			yyt2 = in->cur;
			goto yy175;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy171;
		default:
			if (in->lim <= in->cur) {
				in->state = 145;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy172:
	++in->cur;
yyFillLabel146:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 146;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy176;
		default: goto yy93;
	}
yy173:
	++in->cur;
yyFillLabel147:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 147;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy177;
		default: goto yy93;
	}
yy174:
	++in->cur;
yyFillLabel148:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy178;
		default:
			if (in->lim <= in->cur) {
				in->state = 148;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy175:
	++in->cur;
yyFillLabel149:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy174;
		case ' ': goto yy175;
		default:
			if (in->lim <= in->cur) {
				in->state = 149;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy176:
	++in->cur;
yyFillLabel150:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 150;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy179;
		default: goto yy93;
	}
yy177:
	++in->cur;
yyFillLabel151:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 151;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '\r': goto yy180;
		case ' ': goto yy181;
		default: goto yy93;
	}
yy178:
	++in->cur;
	args = yyt1;
	arge = yyt2;
	in->state = -1;
#line 59 "lexer/mgmt_protocol.re"
	{ result = MGMT_SET_BUFFSIZE; break; }
#line 5943 "./src/mgmt_protocol.re.c"
yy179:
	++in->cur;
yyFillLabel152:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 152;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'A':
		case 'a': goto yy182;
		default: goto yy93;
	}
yy180:
	++in->cur;
yyFillLabel153:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy183;
		default:
			if (in->lim <= in->cur) {
				in->state = 153;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy181:
	++in->cur;
yyFillLabel154:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy180;
		case ' ': goto yy181;
		default:
			if (in->lim <= in->cur) {
				in->state = 154;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy182:
	++in->cur;
yyFillLabel155:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 155;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'T':
		case 't': goto yy184;
		default: goto yy93;
	}
yy183:
	++in->cur;
	in->state = -1;
#line 60 "lexer/mgmt_protocol.re"
	{ result = MGMT_GET_DISSECTOR_STATUS; break; }
#line 6006 "./src/mgmt_protocol.re.c"
yy184:
	++in->cur;
yyFillLabel156:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 156;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'U':
		case 'u': goto yy185;
		default: goto yy93;
	}
yy185:
	++in->cur;
yyFillLabel157:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 157;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'S':
		case 's': goto yy186;
		default: goto yy93;
	}
yy186:
	++in->cur;
yyFillLabel158:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 158;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case ' ': goto yy187;
		case 'o':
			yyt1 = in->cur;
			goto yy188;
		default: goto yy93;
	}
yy187:
	++in->cur;
yyFillLabel159:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy134;
		case ' ': goto yy187;
		case 'o':
			yyt1 = in->cur;
			goto yy189;
		default:
			if (in->lim <= in->cur) {
				in->state = 159;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy188:
	++in->cur;
yyFillLabel160:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 160;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'f': goto yy190;
		case 'n': goto yy191;
		default: goto yy93;
	}
yy189:
	++in->cur;
yyFillLabel161:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 161;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
		case 'f': goto yy192;
		case 'n': goto yy193;
		default: goto yy125;
	}
yy190:
	++in->cur;
yyFillLabel162:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 162;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case 'f': goto yy191;
		default: goto yy93;
	}
yy191:
	++in->cur;
yyFillLabel163:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 163;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
		case '\r': goto yy194;
		default: goto yy93;
	}
yy192:
	++in->cur;
yyFillLabel164:
	yych = *in->cur;
	switch (yych) {
		case 0x00:
			if (in->lim <= in->cur) {
				in->state = 164;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
		case 'f': goto yy193;
		default: goto yy125;
	}
yy193:
	++in->cur;
yyFillLabel165:
	yych = *in->cur;
	switch (yych) {
		case '\r': goto yy194;
		default:
			if (in->lim <= in->cur) {
				in->state = 165;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy124;
	}
yy194:
	++in->cur;
yyFillLabel166:
	yych = *in->cur;
	switch (yych) {
		case '\n': goto yy195;
		default:
			if (in->lim <= in->cur) {
				in->state = 166;
				{ return MGMT_INCOMPLETE; }
			}
			goto yy91;
	}
yy195:
	++in->cur;
	args = yyt1;
	arge = in->cur - 2;
	in->state = -1;
#line 61 "lexer/mgmt_protocol.re"
	{ result = MGMT_SET_DISSECTOR_STATUS; break; }
#line 6176 "./src/mgmt_protocol.re.c"
yy196:
	in->state = -1;
#line 70 "lexer/mgmt_protocol.re"
	{ result = MGMT_INCOMPLETE; break; }
#line 6181 "./src/mgmt_protocol.re.c"
#line 71 "lexer/mgmt_protocol.re"

	}

	end = in->cur;
	*arg = args;
	*argLen = arge - args;
	*len = end - in->tok;
	in->state = -1;
	return result;
}